# Generated by Django 3.1.5 on 2021-05-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterVideo',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('url', models.TextField(blank=True, null=True)),
                ('date_saved_utc', models.DateTimeField()),
                ('parent_tweet_id', models.BigIntegerField()),
                ('slug', models.TextField(blank=True, null=True, unique=True)),
                ('flagged', models.BooleanField(null=True)),
            ],
            options={
                'db_table': 'twitter_videos',
            },
        ),
        migrations.CreateModel(
            name='VideoTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100, unique=True)),
                ('date_created', models.DateTimeField()),
                ('twitter_videos', models.ManyToManyField(to='scraper.TwitterVideo')),
            ],
            options={
                'db_table': 'video_tags',
            },
        ),
    ]
