# Generated by Django 3.1.5 on 2021-06-19 08:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterVideo',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('url', models.TextField(blank=True, null=True)),
                ('date_saved_utc', models.DateTimeField()),
                ('parent_tweet_id', models.BigIntegerField()),
                ('slug', models.TextField(blank=True, null=True, unique=True)),
                ('flagged', models.BooleanField(null=True)),
            ],
            options={
                'db_table': 'twitter_videos',
            },
        ),
        migrations.CreateModel(
            name='VideoTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'video_tags',
            },
        ),
        migrations.CreateModel(
            name='VideoTagTwitterVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twittervideo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='scraper.twittervideo')),
                ('videotag', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='scraper.videotag')),
            ],
            options={
                'db_table': 'video_tags_twitter_videos',
                'unique_together': {('videotag', 'twittervideo')},
            },
        ),
    ]
