# Generated by Django 3.1.5 on 2021-06-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20210419_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twittervideo',
            old_name='date_processed_utc',
            new_name='date_saved_utc',
        ),
        migrations.RenameField(
            model_name='twittervideo',
            old_name='requesting_tweet_id',
            new_name='parent_tweet_id',
        ),
        migrations.RemoveField(
            model_name='twittervideo',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='twittervideo',
            name='tweet_with_video_id',
        ),
        migrations.AddField(
            model_name='twittervideo',
            name='flagged',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
